---
name: Bitcoin
on:
  pull_request:
  push:
    branches:
      - main

jobs:

  molecule:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - distro: ubuntu2004
            impl: core
            version: "30.2"
          - distro: ubuntu2204
            impl: core
            version: "30.2"
          - distro: ubuntu2204
            impl: knots
            version: "29.2.knots20251110"
    steps:
      - uses: actions/checkout@v4

      - name: Test with molecule
        run: make test DISTRO=${{ matrix.distro }} BITCOIND_IMPL=${{ matrix.impl }} BITCOIND_VERSION=${{ matrix.version }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
